name: Build Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max_old_space_size=16384

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.13.0'

    - name: Check npm config
      run: |
        npm config list
        npm config ls -l

    - name: Install Dependencies
      run: npm install --force

    - name: Build Application
      run: npm run build
